name: path-filter
on:
  push:
    paths:
      - '.github/workflows/part1/*'
      - '!.github/workflows/part1/push.yaml'

jobs:
  branch-filter:
    runs-on: ubuntu-latest
    steps:
    - name: echo part1
      run: echo part1

